# Schema for the configuration files of the flexiaccess module.
flexiaccess.settings:
  type: config_object
  label: 'flexiaccess settings'
  mapping:
    example:
      type: string
      label: 'Example'
